blogicum_project/blog/urls.py
# blogicum/blog/urls.py
from django.urls import path

from .views import (CategoryPostsListView, CommentDeleteView, rss_feed, robots_txt_view,
                    CommentUpdateView, IndexView, ListView, PostCommentView,
                    PostCreateView, PostDeleteView, PostDetailView,
                    PostEditView, UserProfileEditView, UserProfileView)
                    

app_name = 'blog'

urlpatterns = [
    path('category/<slug:category_slug>/', CategoryPostsListView.as_view(),
         name='category_posts'),
    path('profile/edit/', UserProfileEditView.as_view(), name='edit_profile'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='profile'),
    path('posts/list/', ListView.as_view(), name='posts_list'),
    path('posts/<int:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', PostCreateView.as_view(), name='create_post'),
    path('posts/<int:post_id>/edit/', PostEditView.as_view(),
         name='edit_post'),
    path('posts/<int:post_id>/delete/', PostDeleteView.as_view(),
         name='delete_post'),
    path(
        'posts/<int:post_id>/comment/',
        PostCommentView.as_view(), name='add_comment'),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        CommentUpdateView.as_view(), name='edit_comment'),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        CommentDeleteView.as_view(), name='delete_comment'),
    path('rss-feed.xml', rss_feed, name='rss_feed'),
    path("robots.txt", robots_txt_view, name="robots_txt"),
    path('', IndexView.as_view(), name='index'),
]

blogicum_project/blogicum/urls.py
# blogicum/blogicum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView

from blog.views import UserRegisterView
from blog.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

handler404 = 'pages.views.custom_404_view'
handler500 = 'pages.views.custom_500_view'
handler403 = 'pages.views.custom_403_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/',
         UserRegisterView.as_view(),
         name='registration'),
    path('ckeditor/', include('django_ckeditor_5.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/img/fav/favicon.ico', permanent=True)),
    path('pages/', include('pages.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blogicum_project/blog/models.py
# blogicum/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import Truncator

from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext_lazy as _
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.timezone import now
from django.core.validators import MaxLengthValidator

from .constants import CHAR_FIELD_MAX_LENGTH, SELF_TEXT_MAX_LENGTH, COMMENT_TEXT_MAX_LENGTH

User = get_user_model()


class PublishableModel(models.Model):
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлено'
    )

    class Meta:
        abstract = True


class TitleModel(models.Model):
    title = models.CharField(
        max_length=CHAR_FIELD_MAX_LENGTH,
        verbose_name='Заголовок'
    )

    class Meta:
        abstract = True


class Location(PublishableModel):
    name = models.CharField(
        max_length=CHAR_FIELD_MAX_LENGTH,
        verbose_name='Название места'
    )

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'
        ordering = ['name']

    def __str__(self):
        return Truncator(self.name).chars(
            SELF_TEXT_MAX_LENGTH, truncate='...')


class Category(PublishableModel, TitleModel):
    description = models.TextField(
        verbose_name='Описание'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.'
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']

    def __str__(self):
        return Truncator(self.title).chars(
            SELF_TEXT_MAX_LENGTH, truncate='...')


class Post(PublishableModel, TitleModel):
    text = CKEditor5Field(config_name='default', verbose_name="Текст публикации")

    image = models.ImageField(
        upload_to='blogs_images/',
        null=True,
        blank=True,
        verbose_name='Изображение'
    )

    pub_date = models.DateTimeField(
        default=now,  # Устанавливает текущее время по умолчанию
        verbose_name='Дата и время публикации',
        help_text=_(
            'Если установить дату и время в будущем — можно делать '
            'отложенные публикации.'
        ),
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор публикации'
    )

    location = models.ForeignKey(
        Location,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Местоположение'
    )

    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Категория'
    )

    class Meta:
        default_related_name = 'posts'
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'
        ordering = ['-pub_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'post_id': self.id})

    def __str__(self):
        return self.title


class Comment(PublishableModel, models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',  # Добавляем related_name
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        validators=[MaxLengthValidator(COMMENT_TEXT_MAX_LENGTH)]
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['created_at']

    def __str__(self):
        return f'Комментарий от {self.author} к посту {self.post}'

blogicum_project/blog/forms.py
# blogicum/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView

from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 5,
                'cols': 40,
                'placeholder': 'Введите ваш комментарий...',
                'class': 'custom-textarea-class',
            }),
        }


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']  # Добавьте поля, которые вам нужны

blogicum_project/blog/views.py
# blogicum/blog/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.db.models import Count
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import DeleteView, DetailView, ListView, UpdateView
from django.views.generic.edit import CreateView

from .constants import NUMBER_OF_POSTS
from .forms import CommentForm, UserRegistrationForm
from .mixins import (AuthorRequiredMixin, PaginatorMixin, 
                     PostQueryMixin, PostCommentCountMixin)
from .models import Category, Comment, Post

from django_ckeditor_5.widgets import CKEditor5Widget


class CommentDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    model = Comment
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('blog:post_detail',
                       kwargs={'post_id': self.object.post.id})
    

class PostDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/create.html'
    pk_url_kwarg = 'post_id'
    def get_success_url(self):
        return reverse('blog:index')
    def handle_no_permission(self):
        return HttpResponseRedirect(self.get_object().get_absolute_url())


class CommentUpdateView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('blog:post_detail',
                       kwargs={'post_id': self.object.post.id})


class PostCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/detail.html'

    def form_valid(self, form):
        post = get_object_or_404(
            Post, id=self.kwargs['post_id'], is_published=True)
        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.post.get_absolute_url()
    

class PostEditView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/create.html'
    fields = ['title', 'text', 'image', 'category', 'location', 'pub_date']
    pk_url_kwarg = 'post_id'
    def get_success_url(self):
        return self.object.get_absolute_url()
    def handle_no_permission(self):
        return redirect(self.get_object().get_absolute_url())
    

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'text', 'image', 'category', 'location', 'pub_date']
    template_name = 'blog/create.html'
    def get_form(self, form_class=None):
        # Получаем форму
        form = super().get_form(form_class)
        # Настраиваем виджет CKEditor для поля "text"
        form.fields['text'].widget = CKEditor5Widget(config_name='default')
        return form
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('blog:profile',
                       kwargs={'username': self.request.user.username})


class UserLoginView(LoginView):
    def get_redirect_url(self):
        return reverse('blog:profile',
                       kwargs={'username': self.request.user.username})


class UserProfileEditView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email']
    template_name = 'blog/user.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('blog:profile',
                       kwargs={'username': self.request.user.username})


class UserProfileView(PostQueryMixin, DetailView,
                      PostCommentCountMixin, PaginatorMixin):
    model = User
    template_name = 'blog/profile.html'
    context_object_name = 'profile'

    def get_object(self):
        username = self.kwargs.get('username')
        return get_object_or_404(User, username=username)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        if self.request.user == user:
            user_posts = self.get_filtered_posts(author=user)
        else:
            user_posts = self.get_filtered_posts(
                author=user, published_only=True)
        context.update(self.get_paginated_context(user_posts))
        return context


class UserRegisterView(CreateView):
    template_name = 'registration/registration_form.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.success_url)


class IndexView(PostQueryMixin, PostCommentCountMixin, PaginatorMixin, ListView):
    model = Post
    context_object_name = 'page_obj'
    template_name = 'pages/index.html'

    def get_queryset(self):
        return self.get_filtered_posts(published_only=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context.update(self.get_paginated_context(queryset))
        return context
    

class ListView(PostQueryMixin, PostCommentCountMixin, PaginatorMixin, ListView):
    model = Post
    context_object_name = 'page_obj'
    template_name = 'blog/posts_list.html'

    def get_queryset(self):
        return self.get_filtered_posts(published_only=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context.update(self.get_paginated_context(queryset))
        return context


class CategoryPostsListView(ListView, PostCommentCountMixin, PaginatorMixin):
    model = Post
    context_object_name = 'page_obj'
    template_name = 'blog/category.html'

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        self.category = get_object_or_404(
            Category, slug=category_slug, is_published=True)
        return self.category.posts.filter(
            is_published=True,
            pub_date__lte=timezone.now()
        ).annotate(
            comment_count=Count('comments')
        ).order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context.update(self.get_paginated_context(queryset))
        context['category'] = self.category
        return context


class PostDetailView(DetailView, PaginatorMixin):
    model = Post
    template_name = 'blog/detail.html'

    def get_object(self):
        post_id = self.kwargs.get('post_id')
        post = get_object_or_404(Post, id=post_id)
        if (
            not post.is_published
            or not post.category.is_published
            or (post.pub_date > timezone.now())
        ) and post.author != self.request.user:
            raise Http404("Пост не опубликован или отложен.")
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = post.comments.select_related(
            'author').order_by('created_at')
        context.update(self.get_paginated_context(comments))
        context['form'] = CommentForm()
        return context


def robots_txt_view(request):
        lines = [
            "User-agent: *",
            "Disallow: /admin/",
            "Allow: /static/",
            "Sitemap: https://kvartirabezvznosa.ru/sitemap.xml",
            "Sitemap: https://kvartirabezvznosa.ru/rss-feed.xml",
        ]
        return HttpResponse("\n".join(lines), content_type="text/plain")


def rss_feed(request):
        """Генерация RSS-канала для лендинга."""
        rss_content = f"""<?xml version="1.0" encoding="UTF-8"?>
        <rss xmlns:yandex="http://news.yandex.ru"
            xmlns:media="http://search.yahoo.com/mrss/"
            xmlns:turbo="http://turbo.yandex.ru"
            version="2.0">
            <channel>
                <title>Карина Дерябина - эксперт по недвижимости</title>
                <link>https://kvartirabezvznosa.ru/</link>
                <description>Подбор лучших квартир под ваш запрос в Москве и Краснодаре</description>
                <language>ru</language>

                <!-- Главная страница -->
                <item turbo="true">
                    <link>https://kvartirabezvznosa.ru/</link>
                    <turbo:content>
                        <![CDATA[
                        <header>
                            <h1>Карина Дерябина - эксперт по недвижимости</h1>
                            <figure>
                                <img src="https://kvartirabezvznosa.ru/static/img/logo.jpg" alt="Логотип Карина Дерябина">
                            </figure>
                            <h2>Карина Дерябина</h2>
                            <p>Подбор лучших квартир в Москве под ваш бюджет</p>
                        </header>
                        <section>
                            <h2>Услуги</h2>
                            <ul>
                                <li>
                                    <figure>
                                        <img src="https://osteopat-violetta.ru/static/img/krivosheya.jpg" alt="Лечение кривошеи">
                                        <figcaption>Лечение кривошеи</figcaption>
                                    </figure>

blogicum_project/templates/blog/category.html
{% extends "base.html" %}
{% block title %}Публикации в категории {{ category.title }}{% endblock %}
{% block content %}
<section class="posts">
  <div class="posts__container">
    <h1 class="posts__heading">Публикации в категории – {{ category.title }}</h1>
    <p class="category__description">{{ category.description }}</p>
    
    <div class="posts__grid">
      {% for post in page_obj %}
        <article class="posts__card">
          {% include "includes/post_card.html" %}
        </article>
      {% endfor %}
    </div>

    <div class="posts__paginator">
      {% include "includes/paginator.html" %}
    </div>
  </div>
</section>
{% endblock %}

blogicum_project/templates/blog/comment.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <section class="comments">
    <h3 class="comments__title">Оставить комментарий</h3>
    <form class="comments__form" method="post" action="{% url 'blog:add_comment' post.id %}">
      {% csrf_token %}
      <label class="comments__label" for="comment-text">Ваш комментарий:</label>
      <textarea 
        id="comment-text"
        name="text"
        class="comments__input"
        placeholder="Введите ваш комментарий..."
        rows="4"
        required
      ></textarea>
      <button class="comments__button" type="submit">Отправить</button>
    </form>
  </section>
{% endif %}

<section class="comments__list">
  {% for comment in page_obj %}
    <article class="comment">
      <div class="comment__header">
        <a href="{% url 'blog:profile' comment.author.username %}" class="comment__author" name="comment_{{ comment.id }}">
          @{{ comment.author.username }}
        </a>
        <time class="comment__date" datetime="{{ comment.created_at }}">
          {{ comment.created_at }}
        </time>
      </div>
      <p class="comment__text">{{ comment.text|linebreaksbr }}</p>
      
      {% if user == comment.author or user.is_superuser %}
        <div class="comment__actions">
          <a href="{% url 'blog:edit_comment' post.id comment.id %}" class="comment__link">Редактировать</a>
          <a href="{% url 'blog:delete_comment' post.id comment.id %}" class="comment__link comment__link--delete">Удалить</a>
        </div>
      {% endif %}
    </article>
  {% endfor %}
</section>

{% include "includes/paginator.html" %}

blogicum_project/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %} | {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
<section class="post">
  <div class="post__container">
    <article class="post__card">
      {% if post.image %}
        <figure class="post__image-container">
          <a class="post__image-link" href="{{ post.image.url }}" target="_blank">
            <img class="post__image" src="{{ post.image.url }}" alt="Изображение для поста {{ post.title }}">
          </a>
        </figure>
      {% endif %}

      <header class="post__header">
        <h1 class="post__title">{{ post.title }}</h1>
        <div class="post__meta">
          {% if not post.is_published %}
            <p class="post__warning">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="post__warning">Выбранная категория снята с публикации админом</p>
          {% endif %}
          <p class="post__info">
            {{ post.pub_date|date:"d E Y, H:i" }} |
            {% if post.location and post.location.is_published %}
              {{ post.location.name }}
            {% else %}
              Планета Земля
            {% endif %}
            <br>
            Автор: <a class="post__link" href="{% url 'blog:profile' post.author.username %}">@{{ post.author.username }}</a>
            <br>
            Категория: <a class="post__link" href="{% url 'blog:category_posts' post.category.slug %}">{{ post.category.title }}</a>
          </p>
        </div>
      </header>

      <section class="post__content">
        <p class="post__text">{{ post.text|safe }}</p>

        <div class="post__share">
          <script src="https://yastatic.net/share2/share.js"></script>
          <div class="ya-share2" data-curtain data-shape="round" data-limit="0"
               data-more-button-type="short"
               data-services="messenger,vkontakte,odnoklassniki,telegram,twitter,viber,whatsapp,moimir,pinterest"></div>
        </div>
      </section>

      <footer class="post__footer">
        {% include "includes/comments.html" %}
      </footer>
    </article>
  </div>
</section>
{% endblock %}

blogicum_project/templates/blog/posts_list.html
{% extends "base.html" %}
{% block title %}Новые посты{% endblock %}
{% block content %}
<section class="posts">
  <div class="posts__container">
    <h1 class="posts__heading">Блог эксперта по недвижимости</h1>
    
    <div class="posts__grid">
      {% for post in page_obj %}
      <article class="posts__card">
        {% include "includes/post_card.html" %}
      </article>
      {% endfor %}
    </div>
    
    <div class="posts__paginator">
      {% include "includes/paginator.html" %}
    </div>
  </div>
</section>
{% endblock %}

blogicum_project/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}Профиль пользователя {{ profile.username }}{% endblock %}
{% block content %}
<!-- Секция с записями пользователя -->
<section class="posts">
  <div class="posts__container">
    <h1 class="posts__heading">Записи пользователя: {{ profile.username }}</h1>
    <div class="posts__grid">
      {% for post in page_obj %}
      <article class="posts__card">
        {% include "includes/post_card.html" %}
      </article>
      {% endfor %}
    </div>
    <div class="posts__paginator">
      {% include "includes/paginator.html" %}
    </div>
  </div>
</section>
{% endblock %}

<!-- Секция профиля 
<section id="profile-header" class="py-5">
  <div class="container text-center">
    <h1 class="section-heading mb-5">Профиль пользователя {{ profile.username }}</h1>
    
    <ul class="list-group list-group-flush mb-4">
      <li class="list-group-item text-muted">
        Имя пользователя:
        {% if profile.get_full_name %}
          {{ profile.get_full_name }}
        {% else %}
          не указано
        {% endif %}
      </li>
      <li class="list-group-item text-muted">
        Регистрация: {{ profile.date_joined|date:"d E Y" }}
      </li>
      <li class="list-group-item text-muted">
        Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}
      </li>
    </ul>
   
    {% if user.is_authenticated and request.user == profile %}
      <div class="d-flex justify-content-center flex-wrap gap-3">
        <a class="btn btn-outline-primary btn-sm" href="{% url 'blog:edit_profile' %}">Редактировать профиль</a>
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'password_change' %}">Изменить пароль</a>
      </div>
    {% endif %}
  
  </div>
</section>
-->

blogicum_project/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}Редактирование профиля {{ request.user.username }}{% endblock %}
{% block content %}
<section class="posts">
  <div class="posts__container">
    <h1 class="posts__heading">Редактирование профиля - {{ request.user.username }}</h1>
    <div class="posts__grid">
      <form class="posts__card" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Отправить" %}
      </form>
    </div>
  </div>
</section>
{% endblock %}