blogicum_project/blog/urls.py
# blogicum/blog/urls.py
from django.urls import path

from .views import (CategoryPostsListView, CommentDeleteView, rss_feed, robots_txt_view,
                    CommentUpdateView, IndexView, ListView, PostCommentView,
                    PostCreateView, PostDeleteView, PostDetailView,
                    PostEditView, UserProfileEditView, UserProfileView)
                    

app_name = 'blog'

urlpatterns = [
    path('category/<slug:category_slug>/', CategoryPostsListView.as_view(),
         name='category_posts'),
    path('profile/edit/', UserProfileEditView.as_view(), name='edit_profile'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='profile'),
    path('posts/list/', ListView.as_view(), name='posts_list'),
    path('posts/<int:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', PostCreateView.as_view(), name='create_post'),
    path('posts/<int:post_id>/edit/', PostEditView.as_view(),
         name='edit_post'),
    path('posts/<int:post_id>/delete/', PostDeleteView.as_view(),
         name='delete_post'),
    path(
        'posts/<int:post_id>/comment/',
        PostCommentView.as_view(), name='add_comment'),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        CommentUpdateView.as_view(), name='edit_comment'),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        CommentDeleteView.as_view(), name='delete_comment'),
    path('rss-feed.xml', rss_feed, name='rss_feed'),
    path("robots.txt", robots_txt_view, name="robots_txt"),
    path('', IndexView.as_view(), name='index'),
]

blogicum_project/blogicum/urls.py
# blogicum/blogicum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView

from blog.views import UserRegisterView
from blog.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

handler404 = 'pages.views.custom_404_view'
handler500 = 'pages.views.custom_500_view'
handler403 = 'pages.views.custom_403_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/',
         UserRegisterView.as_view(),
         name='registration'),
    path('ckeditor/', include('django_ckeditor_5.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/img/fav/favicon.ico', permanent=True)),
    path('pages/', include('pages.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blogicum_project/templates/includes/category_link.html
<!-- blogicum/templates/includes/category_link.html -->
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  {{ post.category.title }}
</a>

blogicum_project/templates/includes/comments.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <section class="comments">
    <div class="comments__container">
      <article class="comments__card">
        <div class="comments__form-container">
          <h3 class="comments__title">Оставить комментарий</h3>
          <form class="comments__form" method="post" action="{% url 'blog:add_comment' post.id %}">
            {% csrf_token %}
            <label class="comments__label" for="comment-text">Ваш комментарий:</label>
            <textarea 
              id="comment-text"
              name="text"
              class="comments__input"
              placeholder="Введите ваш комментарий..."
              rows="4"
              required
            ></textarea>
            <button class="comments__button" type="submit">Отправить</button>
          </form>
        </div>
      </article>
    </div>
  </section>
{% endif %}

<section class="comments">
  <div class="comments__container">
    <article class="comments__card">
      <div class="comments__list">
        {% for comment in page_obj %}
          <div class="comments__item">
            <div class="comments__header">
              <a href="{% url 'blog:profile' comment.author.username %}" class="comments__author" name="comment_{{ comment.id }}">
                @{{ comment.author.username }}
              </a>
              <time class="comments__date" datetime="{{ comment.created_at }}">
                {{ comment.created_at }}
              </time>
            </div>
            <p class="comments__text">{{ comment.text|linebreaksbr }}</p>
          </div>
        {% endfor %}
      </div>
    </article>
  </div>
</section>

{% include "includes/paginator.html" %}

blogicum_project/templates/includes/footer.html
{% load static %}
<footer class="footer">
    <div class="footer__container">
      
      <!-- Секция "О компании" -->
      <div class="footer__section footer__section--about">
        <h2 class="footer__title">Карина Дерябина</h2>
        <p class="footer__description">Эксперт по недвижимости в Москве и Краснодаре.</p>
        <img
            class="footer__logo"
            src="{% static 'images/footer/footer-logo.png' %}"
            alt="Логотип - фронтальное фото лица Карины Дерябиной"
        >
      </div>
  
      <!-- Секция "Полезные ссылки" -->
      <div class="footer__section footer__section--nav">
        <h3 class="footer__title">Полезные ссылки</h3>
        <ul class="footer__list">
          <li class="footer__item"><a href="/" class="footer__link">Главная</a></li>
          <li class="footer__item"><a href="#services" class="footer__link">Услуги</a></li>
          <li class="footer__item"><a href="#about" class="footer__link">О себе</a></li>
          <li class="footer__item"><a href="#contact" class="footer__link">Контакты</a></li>
          <li class="footer__item"><a href="/posts/list/" class="footer__link">Блог</a></li>
        </ul>
      </div>
      
      <!-- Секция "Контакты" -->
      <div class="footer__section footer__section--contacts">
        <h3 class="footer__title">Контакты</h3>
        <ul class="footer__list">
          <li class="footer__item"><a href="https://wa.me/79032354416" class="footer__link">WhatsApp</a></li>
          <li class="footer__item"><a href="tel:+79032354416" class="footer__link">+7 903 235 44 16</a></li>
          <li class="footer__item"><a href="mailto:deryabinakarina@mail.ru" class="footer__link">deryabinakarina@mail.ru</a></li>
          <li class="footer__item"><a href="https://yandex.com/maps/213/moscow/?ll=37.604206%2C55.766132&mode=routes&rtext=~55.766125%2C37.604193&rtt=auto&ruri=~&z=16.83" class="footer__link">Офис: г. Москва, ул. Тверская, 18к1</a></li>
        </ul>
      </div>
  
      <!-- Секция "Социальные сети" -->
      <div class="footer__section footer__section--social">
        <h3 class="footer__title">Мои соцсети</h3>
        <div class="footer__social-links">
            <a href="https://wa.me/79032354416" class="footer__social-icon" aria-label="WhatsApp">
              <i class="fab fa-whatsapp"></i>
            </a>
            <a href="https://t.me/kazhdomu_po_kvartire" class="footer__social-icon" aria-label="Telegram">
              <i class="fab fa-telegram"></i>
            </a>
            <a href="https://instagram.com/kazhdomu_po_kvartire" class="footer__social-icon" aria-label="Instagram">
              <i class="fab fa-instagram"></i>
            </a>
          </div>
      </div>
    </div>
  
    <!-- Нижний блок -->
    <div class="footer__bottom">
      <p class="footer__copy">&copy; 2025 Карина Дерябина - Эксперт по недвижимости</p>
      <a href="https://wa.me/79522672726" class="footer__dev">Разработка: Александр Мясоед</a>
      <a href="/posts/1/" class="footer__policy">Политика конфиденциальности</a>
    </div>
</footer>

blogicum_project/templates/includes/footer_old.html
<!-- Футер -->
<footer class="py-4 bg-dark text-white">
  <div class="container">
    <div class="row text-center text-md-start">
      <!-- Колонка "Полезные ссылки" -->
      <div class="col-12 col-md-4 mb-3">
        <h5>Полезные ссылки</h5>
        <ul class="list-unstyled">
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/">Главная страница</a></li>
          {% if request.path == "/" %}
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#services">Услуги</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#about">О себе</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#mystory">Видео рассказ о себе</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#fotogalery">Фото галерея</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#certificates">Дипломы и сертификаты</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#blog">Новые статьи в блоге</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#video-tur">Видео отзывы клиентов</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#contact">Контакты</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="#social">Социальные сети</a></li>
          {% endif %}
          {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item "><a class="text-reset text-decoration-none py-0" href="/posts/list/">Блог о недвижимости</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/admin/blog/post/add/">Написать пост</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="{% url 'logout' %}">Выйти</a></li>
          {% else %}
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/auth/login/">Войти</a></li>
          <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/auth/registration/">Регистрация</a></li>
          {% endif %}
          {% endwith %}   
        </ul>
      </div>
      <!-- Колонка "Контакты" -->
      <div class="col-12 col-md-4 mb-3">
        <h5>Контакты</h5>
        <ul class="list-unstyled">
          <li><a href="tel:+79052294650" class="text-white text-decoration-none">+7 903 235 44 16</a></li>
          <li><a href="mailto:veta1981@yandex.ru" class="text-white text-decoration-none">deryabinakarina@mail.ru</a></li>
          <li>Москва, ул. Тверская, 18к1, 127006, Россия</li>
        </ul>
      </div>
      
      <!-- Колонка "Социальные сети" -->
      <div class="col-12 col-md-4 mb-3 text-center text-md-start">
        <h5>Мои соцсети</h5>
        <a href="https://wa.me/79032354416" target="_blank" class="text-white me-3" aria-label="WhatsApp">
            <i class="fab fa-whatsapp fa-lg"></i>
        </a>
        <a href="https://t.me/kazhdomu_po_kvartire" target="_blank" class="text-white me-3" aria-label="Telegram">
            <i class="fab fa-telegram fa-lg"></i>
        </a>
        <a href="https://instagram.com/kazhdomu_po_kvartire" target="_blank" class="text-white me-3" aria-label="Инстаграм">
            <i class="fab fa-instagram fa-lg"></i>
        </a>
        <a href="https://www.threads.net/@kazhdomu_po_kvartire" target="_blank" class="text-white me-3" aria-label="Threads">
            <i class="fas fa-comment-dots fa-lg"></i>
        </a>
      </div>

    </div>
    <!-- Нижняя строка с копирайтом -->
    <div class="text-center mt-4">
      <p class="mb-0">&copy; 2025 Эксперт по недвижимости Карина Дерябина</p>
      <a class="text-reset text-decoration-none py-0" href="https://wa.me/79522672726">
        <p class="mb-0">Веб разработчик: Александр Мясоед</p>
      <a class="text-reset text-decoration-none py-0" href="/posts/10/">
        <p class="mb-0">Политика конфиденциальности</p>
      </a>
      </a>
    </div>
  </div>
</footer>

blogicum_project/templates/includes/header.html
{% load static %}
<header class="header">
    <div class="header__left">
        <a href="/" class="header__logo-link">
            <img
            class="header__logo"
            src="{% static 'images/header/header-logo.png' %}"
            alt="Логотип - фронтальное фото лица Карины Дерябиной"
            >
        </a>
        <a href="/" class="header__name-link">
            Карина Дерябина
        </a>
    </div>
    <div class="header__right">
        <button class="hamburger-icon" id="hamburger-icon">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </button>
    </div>

    <!-- Попап меню -->
    <nav class="popup-menu" id="popup-menu">
        <ul class="popup-menu__list">
            <li class="popup-menu__item">
                <a href="/" class="popup-menu__link">Главная</a>
            </li>
            <li class="popup-menu__item">
                <a href="/posts/list/" class="popup-menu__link">Блог</a>
            </li>
            <li class="popup-menu__item">
                <a href="/admin/blog/post/" class="popup-menu__link">Создать запись в блоге</a>
            </li>
            <li class="popup-menu__item">
                <a href="https://www.iloveimg.com/ru" class="popup-menu__link">Обработка изображений</a>
            </li>
            <li>
                <button id="theme-toggle" class="theme-toggle">Сменить тему</button>
            </li>
        </ul>
    </nav>
    
</header>

blogicum_project/templates/includes/header_old.html
{% load static %}
<header>
    <nav class="navbar navbar-light bg-white fixed-top">
        <div class="container d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center logo-section">
                <a href="/" class="navbar-brand d-flex align-items-center">
                    <img src="{% static 'img/logo.png' %}" alt="Фото лица Карина Дерябина" class="rounded-circle logo-spacing" loading="lazy">
                    <span class="ml-3">Карина Дерябина</span>
                </a>
            </div>
    
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/">Главная страница</a></li>
                    {% if request.path == "/" %}
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#services" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Об услуге</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#about" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">О себе</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#mystory" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Видео рассказ о себе</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#fotogalery" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Фото галерея</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#certificates" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Дипломы и сертификаты</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#blog" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Новые статьи в блоге</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#video-tur" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Видео отзывы клиентов</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#contact" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Контакты</a></li>
                        <li class="nav-item"><a class="nav-link text-reset text-decoration-none py-0" href="#social" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Социальные сети</a></li>
                    {% endif %}
                    {% with request.resolver_match.view_name as view_name %}
                    <li class="nav-item "><a class="text-reset text-decoration-none py-0" href="/posts/list/">Блог о недвижимости</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/admin/blog/post/add/">Написать пост</a></li>
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></li>
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="{% url 'logout' %}">Выйти</a></li>
                    {% else %}
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/auth/login/">Войти</a></li>
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/auth/registration/">Регистрация</a></li>
                    {% endif %}
                    {% endwith %}
                    <li class="nav-item"><a class="text-reset text-decoration-none py-0" href="/posts/10/">Политика конфиденциальности</a></li>
                </ul>
                <div class="d-flex align-items-center social-icons">
                    <a class="nav-link px-2" href="https://wa.me/79032354416" target="_blank" rel="noopener" aria-label="WhatsApp">
                        <i class="fab fa-whatsapp"></i>
                    </a>
                    <a class="nav-link px-2" href="https://t.me/kazhdomu_po_kvartire" target="_blank" rel="noopener" aria-label="Telegram">
                        <i class="fab fa-telegram"></i>
                    </a>
                    <a class="nav-link px-2" href="https://instagram.com/kazhdomu_po_kvartire" target="_blank" rel="noopener" aria-label="Инстаграм">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="nav-link px-2" href="https://www.threads.net/@kazhdomu_po_kvartire" target="_blank" rel="noopener" aria-label="Threads">
                        <i class="fas fa-comments"></i>
                    </a>
                </div>
            </div>
        </div>
    </nav>
</header>
<br>

blogicum_project/templates/includes/hero-section.html
{% load static %}

<section class="hero" style="background-image: url('{% static "images/hero-section/moscow-view.jpg" %}');">
    <div class="hero__overlay"></div> <!-- Затемняющий слой -->
    <div class="hero__content">
        <h1 class="hero__title">Хотите купить квартиру в Москве?</h1>
        <button class="hero__button" data-step="1">Да</button>
    </div>
</section>

blogicum_project/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="pagination" aria-label="Навигация по страницам">
    <ul class="pagination__list">
      {% if page_obj.has_previous %}
        <li class="pagination__item">
          <a class="pagination__link pagination__link--arrow" href="?page=1" aria-label="Первая страница">««</a>
        </li>
        <li class="pagination__item">
          <a class="pagination__link pagination__link--arrow" href="?page={{ page_obj.previous_page_number }}" aria-label="Предыдущая страница">«</a>
        </li>
      {% endif %}

      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="pagination__item pagination__item--active">
            <span class="pagination__link pagination__link--active" aria-current="page">{{ i }}</span>
          </li>
        {% else %}
          <li class="pagination__item">
            <a class="pagination__link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="pagination__item">
          <a class="pagination__link pagination__link--arrow" href="?page={{ page_obj.next_page_number }}" aria-label="Следующая страница">»</a>
        </li>
        <li class="pagination__item">
          <a class="pagination__link pagination__link--arrow" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Последняя страница">»»</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

blogicum_project/templates/includes/post_card.html
<article class="post-card">
  {% if post.image %}
  <figure class="post-card__image-container">
    <img class="post-card__image" src="{{ post.image.url }}" alt="Изображение карточки: {{ post.title }}">
  </figure>
  {% endif %}

  <section class="post-card__body">
    <header class="post-card__header">
      <h4 class="post-card__title">{{ post.title }}</h4>
    </header>

    {% if not post.is_published %}
      <p class="post-card__status post-card__status--danger">Пост снят с публикации админом</p>
    {% elif not post.category.is_published %}
      <p class="post-card__status post-card__status--danger">Выбранная категория снята с публикации админом</p>
    {% endif %}

    <p class="post-card__meta">
      {{ post.pub_date|date:"d E Y, H:i" }} | 
      {% if post.location and post.location.is_published %}
        {{ post.location.name }}
      {% else %}
        Тестовый текст
      {% endif %}
      <br>
      Автор <a class="post-card__author" href="{% url 'blog:profile' post.author.username %}">@{{ post.author.username }}</a>
      <br>
      Категория {% include "includes/category_link.html" %}
    </p>

    <footer class="post-card__footer">
      <a href="{% url 'blog:post_detail' post_id=post.id %}" class="post-card__button post-card__button--primary">Читать пост</a>
      <a href="{% url 'blog:post_detail' post_id=post.id %}" class="post-card__button post-card__button--secondary">
        Комментарии ({{ post.comment_count }})
      </a>
    </footer>
  </section>
</article>

blogicum_project/templates/includes/slider.html
<section class="slider">
    <div class="slider__container">
        <button class="slider__arrow slider__arrow--left" aria-label="Предыдущий слайд">&#10094;</button>
        <div class="slider__inner">
            <div class="slider__track">
                <div class="slider__slide">
                    <img src="https://kvartirabezvznosa.s3.cloud.ru/media/slider/slider-image-03.jpeg" alt="Слайд 1" class="slider__image">
                </div>
                <div class="slider__slide">
                    <img src="https://kvartirabezvznosa.s3.cloud.ru/media/slider/slider-image-02.jpeg" alt="Слайд 2" class="slider__image">
                </div>
                <div class="slider__slide">
                    <img src="https://kvartirabezvznosa.s3.cloud.ru/media/slider/slider-image-03.jpeg" alt="Слайд 3" class="slider__image">
                </div>
            </div>
        </div>
        <button class="slider__arrow slider__arrow--right" aria-label="Следующий слайд">&#10095;</button>
        <div class="slider__dots"></div>
    </div>
</section>

blogicum_project/templates/includes/video-reviews.html
{% load static %}
<!-- Видео отзывы -->
<section class="video-reviews">
    <div class="video-reviews__container">
        <h2 class="video-reviews__heading">Видео отзывы</h2>
        <div class="video-reviews__grid">
            <div class="video-reviews__item">
                <video class="video-reviews__video" controls>
                    <source src="{% media 'blogs_videos/otziv-001.mp4' %}" type="video/mp4">
                </video>
            </div>
            <div class="video-reviews__item">
                <video class="video-reviews__video" controls>
                    <source src="{% media 'blogs_videos/otziv-001.mp4' %}" type="video/mp4">
                </video>
            </div>
        </div>
    </div>
</section>